#
# makefile for wrapexec, Borland MAKE
#

# -5      Pentium Instructions
# -C      Allow nested comments
# -Ox     Optimizations
# -d      Merge duplicate strings
# -Wx     Create Windows app
# -M      Generate link map

CFLAGS = -5 -C -O1 -d -WU -M
RM = del

all: wrapexec.exe

wrapexec.exe: wrapexec.cpp wrapexec.res
	$(CC) $(CFLAGS) wrapexec.cpp
	$(RC) wrapexec.rc
	upx -q -q --lzma --compress-icons=0 $@

clean:
	$(RM) wrapexec.obj
	$(RM) wrapexec.res
	$(RM) wrapexec.tds
	$(RM) wrapexec.map
	$(RM) wrapexec.exe

