#
# makefile for wrapexec
#

# -5      Pentium Instructions
# -C      Allow nested comments
# -Ox     Optimizations
# -d      Merge duplicate strings
# -Wx     Create Windows app
# -M      Generate link map

CFLAGS = -5 -C -O1 -d -WU -M

all: wrapexec.exe gv.exe pwd.exe

wrapexec.exe: wrapexec.cpp wrapexec.rc
	$(CC) $(CFLAGS) wrapexec.cpp
	brc32 wrapexec.rc
	upx -q -q --lzma --compress-icons=0 $@

gv.exe: wrapexec.exe
	copy /y $** $@

pwd.exe: wrapexec.exe
	copy /y $** $@

clean:
	if exist wrapexec.obj del wrapexec.obj
	if exist wrapexec.res del wrapexec.res
	if exist wrapexec.tds del wrapexec.tds
	if exist wrapexec.map del wrapexec.map
	if exist wrapexec.exe del wrapexec.exe
	if exist gv.exe del gv.exe
	if exist pwd.exe del pwd.exe

