#
# makefile for wrapexec, Borland MAKE
#

# -5      Pentium Instructions
# -C      Allow nested comments
# -Ox     Optimizations
# -d      Merge duplicate strings
# -Wx     Create Windows app
# -M      Generate link map

PRJ = wrapexec

CFLAGS = -5 -C -O1 -d -WU -M
RM = del

all: $(PRJ).exe

$(PRJ).exe: $(PRJ).cpp $(PRJ).rc $(PRJ)1.ico $(PRJ)2.ico
	$(CC) $(CFLAGS) $(PRJ).cpp
	brc32 $(PRJ).rc
	upx -q -q --lzma --compress-icons=0 $@

clean:
	$(RM) $(PRJ).obj
	$(RM) $(PRJ).res
	$(RM) $(PRJ).tds
	$(RM) $(PRJ).map
	$(RM) $(PRJ).exe

